#ifndef ASSEMBLER_H
#define ASSEMBLER_H

/**
 * @file assembler.h
 * @brief This header file defines the core components and constants for the assembler.
 *
 * It includes necessary standard libraries and other project-specific headers.
 * It also defines file extensions for the various output files generated by the
 * assembler and other critical constants used throughout the program.
 * The external declaration for the `RESERVED_WORDS` array is also included here,
 * making it accessible to all parts of the project that need to check for
 * reserved keywords.
 */

/* --- Standard Library Includes --- */
#include <stdio.h>      /* Standard Input/Output functions. */
#include <stdlib.h>     /* General utilities, including memory allocation. */
#include <ctype.h>      /* Character handling functions. */
#include <string.h>     /* String manipulation functions. */

/* --- Project-Specific Header Includes --- */
#include "data.h"           /* Custom data structures for the assembler. */
#include "pre_assembler.h"  /* Prototypes and definitions for the pre-assembler stage. */
#include "code.h"           /* Definitions related to code and instruction handling. */

/* --- File Extension Constants --- */
#define END_EN_FILE_NAME ".ent"         /**< Suffix for the entry file. */
#define END_EX_FILE_NAME ".ext"         /**< Suffix for the external file. */
#define END_OBJECT_FILE_NAME ".ob"      /**< Suffix for the object file. */
#define END_SOURCE_FILE_NAME ".as"      /**< Suffix for the assembly source file. */
#define END_OF_MACRO_FILE_NAME ".am"    /**< Suffix for the pre-assembled (macro-expanded) file. */

/* --- Other Constants --- */
#define MAX_LEN_OF_STRING_END 4         /**< The maximum length of a file extension string. */
#define EXIT 10000                      /**< A custom return value to indicate a critical exit condition. */

/**
 * @brief A constant array of reserved words.
 *
 * This array contains strings that are reserved keywords in the assembly language,
 * such as instruction names and register names. It is declared as `extern` to
 * indicate that its definition exists in another source file, allowing other
 * files to access its contents.
 */
extern const char *RESERVED_WORDS[];

#endif /* ASSEMBLER_H */
